// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Peers.Persistence;

#nullable disable

namespace Peers.Persistence.Migrations
{
    [DbContext(typeof(PeersDbContext))]
    [Migration("20260307054921_AddSpotlights")]
    partial class AddSpotlights
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("Peers.Spotlights.Internal.PairingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FollowerDancerId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LeaderDancerId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("PairingEntity");
                });

            modelBuilder.Entity("Peers.Spotlights.Internal.SpotlightRoundEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("SpotlightRoundEntity");
                });

            modelBuilder.Entity("Peers.Training.Dancers.DancerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DancerEntity");
                });

            modelBuilder.Entity("Peers.Training.Sessions.Internal.ParticipantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DancerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DancerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Token")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DancerId");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasFilter("Token IS NOT NULL");

                    b.HasIndex("SessionId", "DancerName")
                        .IsUnique();

                    b.ToTable("ParticipantEntity");
                });

            modelBuilder.Entity("Peers.Training.Sessions.Internal.SessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InviteCode")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InviteCode")
                        .IsUnique()
                        .HasFilter("InviteCode IS NOT NULL");

                    b.ToTable("SessionEntity");
                });

            modelBuilder.Entity("Peers.Spotlights.Internal.PairingEntity", b =>
                {
                    b.HasOne("Peers.Spotlights.Internal.SpotlightRoundEntity", null)
                        .WithMany("Pairings")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Peers.Training.Sessions.Internal.ParticipantEntity", b =>
                {
                    b.HasOne("Peers.Training.Dancers.DancerEntity", null)
                        .WithMany()
                        .HasForeignKey("DancerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Peers.Training.Sessions.Internal.SessionEntity", "Session")
                        .WithMany("Participants")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Peers.Spotlights.Internal.SpotlightRoundEntity", b =>
                {
                    b.Navigation("Pairings");
                });

            modelBuilder.Entity("Peers.Training.Sessions.Internal.SessionEntity", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
